### ISSUE TITLE
UART incomplete messages issue!

### ISSUE THREAD

**Issue by mzahana** [mavlink-router/mavlink-router#133]
Hi,

I have the following setup.
1. ODROID connected to Pixhawk (running PX4) via serila port at 921600 (/dev/ttyUSB0)
2. ODROID running mavros and ground bridged to ```gcs_rul:=udp://@127.0.0.1:14550```
3. A 3DR 433MHz connected to ODROID via USB cable (/dev/ttyUSB1) @ 57600
4. mavlink-router routing between ```127.0.0.1:14550``` and the 3DR telemetry module
```mavlink-routerd  127.0.0.1:14550 /dev/ttyUSB1:57600 ```
5. QGC control connected to another 3DR telemetry module

The connection is working but there is a very noticeable delay and I get the following messages from mavlink-router
```
mavlink-routerd  127.0.0.1:14550 /dev/ttyUSB1:57600
Could not open conf file '/etc/mavlink-router/main.conf' (No such file or directory)
Open UART [4] /dev/ttyUSB1 *
UART [4] speed = 57600
Open UDP [5] 127.0.0.1:14550 *
Open TCP [6] 0.0.0.0:5760 *
Endpoint UART [4]: 99 incomplete messages in the last 5 seconds
Endpoint UART [4]: 112 incomplete messages in the last 5 seconds
Endpoint UART [4]: 113 incomplete messages in the last 5 seconds
```

What could be the issue/

Thanks.

**Comment by lucasdemarchi** [comment]
Apparently baudrate for usb0 are not matching. Try to simplify your setup to check for problems in each part. You can remove macros for tests purpose and add the endpoint to mavlink-router

**Comment by mzahana** [comment]
USB0 is used by mavros. But USB1 is for the telem and used by mavlink-router. Also, the connection is established to QGC and I can see the HUD. However, there is a noticeable delay. For example, if I move the drone, the HUD takes some time to reflect.

What macros are you referring to?

**Comment by zehortigoza** [comment]
Run mavlink-router with reports(-r) and paste here please but my guess it that the stream rate is too high for the 3DR telemetry module running at 57000bps, so several messages are not complete written to UART TX buffer and not transmitted.

**Comment by lucasdemarchi** [comment]
I meant mavros. You have 921600 baud to talk to pixhawk but only 57600 to send to QGC. If you have enough data going through the first link it will obviously not fit the speed of the second one. It will be buffered by mavlink-router until the buffer isn't big enough anymore and then you will start seeing message drops.

The way to get this working is to request different stream rate for the messages you are interested in and then create filtering capability in mavlink-router so you don't send those messages through the slow link. It'd be a good contribution.

What I said about mavros is that from your description you actually don't need it. And if you need it (e.g. you are using Ros nodes on Aero), it'd be better  if you connect mavros to mavlink-router, not the other way around.

**Comment by mzahana** [comment]
Yes. I am using ROS. I need mavros fo communicate with pixhawk and I have another note that communicates with both mavros and with ground station. Also I need  long range link so wifi is not my best option. This is why I am using 3DR telemetry but will shift to RFD900 soon.

Now what you mentioned about connecting mavros to mavlink-router, you mean
1. mavlink-router connects to pixhawk smd routes to a udp
2. Mavros connects to udp smd bridges to QGC via telem module?

**Comment by mzahana** [comment]
So I got this working with the following setup.
1. Mavlink-router connects directly to Pixhawk using the serial link 57600 and routes this to two ends. One is a udp to communicate with mavros.  The other ends is to another serial link which is the telemetry to QGC.
