### ISSUE TITLE
How can I open two mavlink ports 

### ISSUE THREAD

**Issue by ivanalexo** [mavlink-router/mavlink-router#146]
I know that by default mavlink listens at port 5760 but I wonder, how can I open another port like 5762?? I mean having two ports for mavlink connection, that's because I'm trying some scripts.
I hope you can help me

**Comment by ivanalexo** [comment]
Thanks for your answer, and yes I've tried to add a tcp entry configurating main.conf like in the example, but by restarting the mavlink-route service and doing netstat -lntu the the new entry is not listening.

**Comment by lucasdemarchi** [comment]
They are different. If you add a TCP endpoint it will be the client side, i.e. it will try to connect somewhere. This is useful for mavlink-router to connect to sitl for example.

I think we used to have support for a server side TCP endpoint but it got removed since we added a more generic one that can accept many connections.

**Comment by ivanalexo** [comment]
I asked this because I'm working with an Intel Aero RTF Drone and I have one script running in the aero compute board which connects locally and I have another program from another PC when I tried to connect to the board remotely sometimes the connection says: link time out.

**Comment by zehortigoza** [comment]
Oh Lucas is right, actual code only open one TCP server port.
@ivanalexo link timeout error is probably due WiFi low signal or something related, 2 TCP server ports will not fix it for you.

**Comment by ivanalexo** [comment]
Se lo, thanks guys for your support, so multiple clients can connect to the same TCP port?? I'll check that and the issues with wifi. Thanks.

**Comment by reluctantgithubuser** [comment]
I LOVE mavlink-router.
For the use case where you have two ground control stations (GCS), e.g. Mission Planner, connected to the same TCP port on one end, the the UAV  flight controller on the other end, which GCS is in control?
It seems that the UAV flight controller responds to commands from both GCSs and also sends telemetry data to both GCSs.
Is there anything to worry about regarding conflicts between two GCSs controlling one UAV?

**Comment by lucasdemarchi** [comment]
You are right that both GCSs are in control, and this gives you the "opportunity" to shoot yourself on the foot.  If both GCSs are implemented correctly, it should work.

**Comment by jbeyerstedt** [comment]
It seems to me, that this question is answered. Please comment, if I should re-open it.
