### ISSUE TITLE
The upload task timeout

### ISSUE THREAD

**Issue by roseyangyu** [mavlink-router/mavlink-router#170]
I use mavlink-router in pc.I use tcp to connect with FC by mavlink-router.And other machine,use udp to connect at the same time.When I upload task by one machine,FC return timeout.Why is that?How do I fix that?

**Comment by lucasdemarchi** [comment]
What upload task are you talking about?
 Please copy and paste the error message

**Comment by roseyangyu** [comment]
I upload some waypoints by QGC.FlyContral return "operation timeout"

**Comment by lucasdemarchi** [comment]
it seems outside of mavlink-router.

**Comment by jbeyerstedt** [comment]
I'll close this because of inactivity for now. Just comment, if you have any updates.
