### ISSUE TITLE
TCP server rejects connections after first connection closes

### ISSUE THREAD

**Issue by highfreq** [mavlink-router/mavlink-router#214]
I can connect to TCP server on port 5790 ( i changed port ) with no problem the first time with pymavlink from my application. Once i close my application i can see mavlink-router closing the connection in status of the service. If i try to connect again than it doesn't connect anymore unless i restart mavlink-router service.
This is the error i get from pymavlink:
ConnectionRefusedError: [WinError 10061] Impossible to establish a connection. Persistent decline from remote computer
Using it to connect Ardupilot to my application on pc.

**Comment by highfreq** [comment]
Ok, investigated a bit more, the service closes once i close my application, that is why it doesn't answer on second try. I solved it by changing the following in service file:
Restart=Always
commented restart time
Now it restarts immediately after i close my connection and works on second attempt.

**Comment by lucasdemarchi** [comment]
Do you mean mavlink-router stops after you close your app?

**Comment by Jaeyoung-Lim** [comment]
@highfreq For me this is not the case, I can connect / reconnect multiple times from QGC

**Comment by highfreq** [comment]
Yes it closes if i open/close my app or MP multiple times.
I solved it by restart=always

**Comment by highfreq** [comment]
Don't know if it was clear in my previous comments but mavlink-router closes only if i use connections to the tcp server. If i use udp it doesn't happen.

**Comment by agrueing** [comment]
This one can probably be closed, resolved by https://github.com/intel/mavlink-router/commit/555bd0150f1043387f4b158f586bda504c6ee038

Found this issue investigating similar behavior when killing apmplanner2 while params were still downloading, turns out the version I was using was built from master around the beginning of May.
