### ISSUE TITLE
Please add instructions for using message filtering feature

### ISSUE THREAD

**Issue by aseyfi** [mavlink-router/mavlink-router#255]
Hello,

Thank you for sharing this great work. Would you please update the instructions or the example config file to show how to enable message filtering?

Thank You,
Ahmad

**Comment by jbeyerstedt** [comment]
Please take a look at Pull Request #238. This will add a description of the config option to the example config. But keep in mind, that filtering is currently only enabled at the UDP endpoints (the PR will add support to all endpoint types).
