### ISSUE TITLE
Intel aero help for development

### ISSUE THREAD

**Issue by galeots** [mavlink-router/mavlink-router#258]
I've bought the intel aerial computer board, I'd like to have some clarification about the flight control. Can you please share with me the flight controller diagrams in which there is the micro smt32mci with the following pinout of the intel aero computer board, where it should be connected and the related reservated connectors (how you can see in photos).
Can you send me the esc technical specifications in order to buy something that might be fine, or can you please share with me the wiring diagrams?
I'm trying to copy your project, since it's out of production, and I hope you don't mind sharing informations. Nowadays the is nothing similar on the market, but if you can help me with diagrams or technical specification as accurate as possible, I'd really appreciate it.
Thank you for your help. 
![fcm](https://user-images.githubusercontent.com/6709995/113286618-bf0a6a00-92ec-11eb-8ba7-2935b80dd9f9.png)
![Immagine](https://user-images.githubusercontent.com/6709995/113286619-bfa30080-92ec-11eb-9c17-b96f3131c98f.png)
![373973-zero](https://user-images.githubusercontent.com/6709995/113287566-0b09de80-92ee-11eb-84de-af376cd09b72.jpeg)

**Comment by jbeyerstedt** [comment]
This project is about the mavlink-router software, which can route MAVlink packets between multiple UDP, TCP and UART interfaces. It was started at intel, but this is NOT an intel project any more!

So we can't help you getting support for intel hardware. My only recommendation would be, that you might find somebody on the PX4 or ArduPilot forums, who could help you. But there's no guarantee on that.
