### ISSUE TITLE
Specification of MAVLink Router's Intended Behavior

### ISSUE THREAD

**Issue by jbeyerstedt** [mavlink-router/mavlink-router#284]
As seen in #283 and some other questions risen by users, not everybody is on the same page how MAVLink Router should actually behave. So I quickly started to write down how I imagine the functionality goal: https://gist.github.com/jbeyerstedt/c6df961612d4f544eb307fa168b68062

Actually there are just minor (but important) differences to the current behavior at the UDP endpoint and how the message filters should move forward. Everything else should match how it's currently implemented.

Open questions are:
- What should the `eavesdropping` mode be, actually? Just dumping out all messages going through the router (no filtering) while ignoring incoming messages on that endpoint? Or basically the same as the normal UDP endpoint but just having all the message filters disabled (allowing receiving messages)?
- Which message filters are needed/ should be implemented? Currently there's just an outgoing allow-list for message IDs. I needed an outgoing allow-list for component IDs (see #238) once. So:
  - Are outgoing filters enough?
  - Are allow-lists enough or do we need block-lists, too?
  - By which fields should we filter?

**Comment by lucasdemarchi** [comment]
@patrickelectric  humn... UDP server mode is what pymavlink calls "udpin". Do you know if mavproxy/mavutil supports multiple clients? I don't think so, as when using mavutil we always have to wait for a heartbeat to read the src port. And I think pymavlink "locks" onto it forever.

In theory it could be possible to learn the src ports and send to all of them when sending. Problem here is that unlike tcp, we will have no idea when/if a client disconnected. We could auto-kill endpoints that were dynamically created after X seconds of inactivity. That might work

**Comment by jbeyerstedt** [comment]
Regarding multiple clients on one UDP "server" endpoint: As noted by Lucas, detecting when a client has disconnected isn't supported by UDP. And the implementation of a server-mode UdpEndpoint would need to be completely different from the client-mode UdpEndpoint -- not creating an endpoint instance right away but adding a new one for each client (like TcpServerPort).
So I would propose to keep the UdpEndpoint's functionality as `udpin`/ `udpout` and add the UDP server functionality the same way as `TcpServerPort`.

**Comment by jbeyerstedt** [comment]
Original topic is closed by #327. Please move your wish for a UDP server to a new issue, it it's still up to date.
