### ISSUE TITLE
Compiled from master this morning and no logs

### ISSUE THREAD

**Issue by highfreq** [mavlink-router/mavlink-router#309]
I just compiled and installed from master and log is not written anymore. Configuration file is same as before with log destination directory configured and dialect specified.
If i start mavlink-router from command line i see no log being created or any feedback from the software telling me log has been started or similar.
If i start it with the -l option from command line than it creates the file.

This is what i have for logging in my main.conf

MavlinkDialect=auto
Log=/home/pi/Logs
LogMode=always

It looks like it ignores Log configuration from conf file.

**Comment by lucasdemarchi** [comment]
Fix in #310. Thanks for the report
