### ISSUE TITLE
How do I forward MAVLink packets from a UART endpoint to another?

### ISSUE THREAD

**Issue by darshan-k-s** [mavlink-router/mavlink-router#357]
I have a PC that has a UART link through RFD900x to my drone. I also have a USB connection to an RPi. I need the MAVLink messages on the RPi for separate purposes and an ethernet connection is not possible due to it already being used. Can I have UART to UART routing?

**Comment by jbeyerstedt** [comment]
With a [config file](https://github.com/mavlink-router/mavlink-router#conf-file) you can have as many UART endpoints as you like. Just the configuration via CLI parameters is quite limited.

A `/etc/mavlink-router/main.conf` on your PC like this should work:
```
[General]
TcpServerPort = 0

# UART link to drone
[UartEndpoint uav]
Device = /dev/ttyFoo
Baud = 115200

# USB TTY to Raspberry Pi
[UartEndpoint rpi]
Device = /dev/ttyBar
Baud = 115200
```
(Obviously you need to exchange the device entries with your actual TTY devices and use the correct baud rate.)
