### ISSUE TITLE
QGroundControl does not connect to Pixhawk

### ISSUE THREAD

**Issue by danielfhnw** [mavlink-router/mavlink-router#361]
## Background
I want to route the telemetry data from my pixhawk 4 flightcontroller to my laptop as the ground station. The routing part does a raspberry pi zero connected through a zerotier network to the laptop and over the GPIO pins to the flightcontroller. 
To implement this I mostly followed the tutorial on [https://bellergy.com/](url).

## Problem
QGroundControl does not connect to Pixhawk when using following command to route (127.0.0.1:4000 is included so i can see the broadcast messages in the sender example): 

![settings_mavlink_router](https://user-images.githubusercontent.com/93777297/165965359-a50069aa-8ce2-4da1-86ce-78a04a8d3905.png)

These are my Comm Links settings:

![qgc_comm_link](https://user-images.githubusercontent.com/93777297/165964653-37fde08c-3bf9-442a-8836-c6d05cbe36a5.png)

Following are tests I did to rule out different subsystems.

Any help would be greatly appreciated.

## Tests
- I tested the mavlink-router with the sender and receiver examples.

![Output_receiver_example](https://user-images.githubusercontent.com/93777297/165963810-a36ed3f1-81b9-469d-83e9-dce7cbf9ba49.png)
Because of that I rule out a build failure or else.

- The output of the sender example even displayed my telemetry data, therefore I also rule out a UART connection problem.

![Ouput_sender_example](https://user-images.githubusercontent.com/93777297/165963920-038db797-bfb5-4b31-9b51-f5f5ccb1ca7a.png)

I am using the following config file: 

![mavlink_router_config](https://user-images.githubusercontent.com/93777297/165964215-ad0cd6b9-15d9-48d8-ac4f-fa725579417c.png)

- I also checked the baudrate and can confirm that MAV_0_RATE is also 57600.
- The zerotier addresses are also correct and I can confirm that the network works, as I am connected to the pi via ssh.
- QGroundControl recognizes the flightcontroller when connected directly through usb

**Comment by lucasdemarchi** [comment]
Possible issues:
1) is the IP of the machine running QGC correct? Is it possible that the IP changed and you didn't notice?
2) Any firewall on the machine running QGC preventing the packet from arriving?

An additional test: since you also have a TCP Server Endpoint, try to add it in QGC passing the IP of the drone to check if you can establish connection the other way around.

**Comment by danielfhnw** [comment]
Thank you for your help.

Switching from UDP to TCP in QGC did the trick.

**Comment by lucasdemarchi** [comment]
switching to TCP is a good experiment to see where things are failing. It seems either the IP for the QGC host given above is wrong or you have a firewall or something else preventing it. The communication via UDP should still work.
