### ISSUE TITLE
Endpoints for one direction

### ISSUE THREAD

**Issue by whoim2** [mavlink-router/mavlink-router#389]
I am trying to create a ground station that works with wifibroadcast. Wfb supports sending data like air_tx > gs_rx & gs_tx > air_rx as udp ports on localhost.
In total, I have port 14550 on gs: 127.0.0.1 in order to send telemetry data to air and 14551 in order to receive it from air. Essentially, this requires one udp endpoint, which should send messages to one uart port and receive from another. I create two endpoints and even connect them via a group, I can see data being received over the air but I can't send anything. I suspect that the endpoint for receiving data over the air immediately sends it to all other points, including the one intended for transmission, and a loop occurs, creating a load on the channel. How should I set up the endpoints in the sample workflow? I guess if the endpoints had a parameter like direction (in, out, both by default) that would solve my problem.

**Comment by jbeyerstedt** [comment]
By default, each message received on one endpoint will be transmitted on all other endpoints. So if you have two endpoints for the same link, mavlink-router will try to loop the received message back to your "wifibroadcast" link. (I don't know, if wifibroadcast already prevents data being sent out again on the "receiving" port.)
The other issue might be, that data with a target address (like parameter requests) will only be transmitted on endpoints, if the system has connected on this endpoint. You should be able to check this, if you get "x messages to unknown endpoints" in the log.
Both issues should be solved by adding the two endpoints to the same group (see [readme](https://github.com/mavlink-router/mavlink-router#message-routing) and scroll to the "Endpoint groups:" heading).

To actually prevent data being sent, you could try to set one of the outgoing message filters to something not used.
