### ISSUE TITLE
Mavlink-router doesn't works.

### ISSUE THREAD

**Issue by Ultramarine1939-syujie** [mavlink-router/mavlink-router#405]
```
cat@lubancat:~/mavlink-router$ mavlink-routerd
mavlink-router version 808a3ee
Could not open conf file '/etc/mavlink-router/main.conf' (No such file or directory)
Opened TCP Server [4] [::]:5760
```
When I build up the program with the guided,this error appears,Could anyone tell me how to fix it?

**Comment by qsantos** [comment]
For anyone wondering, this is just a warning. You can run `mavlink-routerd` without a configuration file; just ignore the “Could not open conf file” line.
