### ISSUE TITLE
Mention malvink udp C++ lib in mavlink-router readme?

### ISSUE THREAD

**Issue by eMrazSVK** [mavlink-router/mavlink-router#433]
Hello guys,

So I've finally finished C++ Mavlink interface. We use it with mavlink-router for many of Airvolute applications and it works great. I know that lot of people struggle with receiving/sending messaging directly from C++. I think this could complete the ecosystem around Mavlink, together with your mavlink-router. So I am thinking is it worth for you to mention that this exists in readme here?

- https://gitlab.com/airvolute_oss/dronecore.os/mavlink-udp-interface -> Main Mavlink C++ library
- https://gitlab.com/airvolute_oss/dronecore.os/mavlink-udp-comm-template -> Template application showcasing the functionality

**Comment by jbeyerstedt** [comment]
I would rather put this in the "show and tell" section of the GitHub discussions.
