### ISSUE TITLE
1 messages to unknown endpoints in the last 5 seconds

### ISSUE THREAD

**Issue by 1776340526** [mavlink-router/mavlink-router#434]
I wanted to use the mavlink-router to connect px4 and qgc. I connected the px4 to /dev/ttyACM of the Raspberry PI and configured port 1.92.***.***, 5760 for forwarding to the public network. The following error is now reported.
![b8edb862ed21f6fa2059575d064fe62](https://github.com/user-attachments/assets/0beba22b-da40-4792-8347-e5b1d8b561f2)
![3e40c2aa93441e851c5ae7db74aa2a6](https://github.com/user-attachments/assets/c5e6ef8a-7996-49f0-8018-8fd51eee0c47)

**Comment by jbeyerstedt** [comment]
First a few questions regarding your config:
- What is listening on port 5760 at 1.92.127.128? As far as I know QGC is only listening for UDP traffic on port 14550
- Who is connecting to the Raspberry Pi on port 5760? mavlink-router has a TCP server at that port if not disabled (see [examples/config.sample](https://github.com/mavlink-router/mavlink-router/blob/master/examples/config.sample#L49))

**Comment by 1776340526** [comment]
> 首先，关于您的配置有几个问题：
> 
> * 在 1.92.127.128 的端口 5760 上侦听什么？据我所知，QGC 仅侦听端口 14550 上的 UDP 流量
> * 谁在端口 5760 上连接到 Raspberry Pi？如果未禁用，mavlink-router 在该端口上有一个 TCP 服务器（参见 [examples/config.sample](https://github.com/mavlink-router/mavlink-router/blob/master/examples/config.sample#L49))

Port 5760 is the port that I forward to the public network, and my QGC has set tcp to connect to port 5760 of the public network.
![1725589357059](https://github.com/user-attachments/assets/036193be-c1b3-4cd1-b7af-25e343bd9934)
Did I set port 5760 again? My 5760 was forwarded to the public network, so I set port 5760 like this.

**Comment by 1776340526** [comment]
> First a few questions regarding your config:
> 
> * What is listening on port 5760 at 1.92.127.128? As far as I know QGC is only listening for UDP traffic on port 14550
> * Who is connecting to the Raspberry Pi on port 5760? mavlink-router has a TCP server at that port if not disabled (see [examples/config.sample](https://github.com/mavlink-router/mavlink-router/blob/master/examples/config.sample#L49))

I tried udp again in ubuntu and it also got an error. Below is a screenshot of the configuration and errors.
![729e9a0732169ef5213fcfaef2f3344](https://github.com/user-attachments/assets/0e1459d3-5a94-4fd3-ae8e-7e10ae604743)
![c678616a7dc6579d686c81e0b3bf748](https://github.com/user-attachments/assets/7ce5b778-dfc7-4fc4-b3e5-4e87f3a189f3)

**Comment by 1776340526** [comment]
> First a few questions regarding your config:
> 
> * What is listening on port 5760 at 1.92.127.128? As far as I know QGC is only listening for UDP traffic on port 14550
> * Who is connecting to the Raspberry Pi on port 5760? mavlink-router has a TCP server at that port if not disabled (see [examples/config.sample](https://github.com/mavlink-router/mavlink-router/blob/master/examples/config.sample#L49))

I think I found the problem. Since the Raspberry PI's port 5760 has been forwarded to the public network, I don't need to do any other configuration.
![b4663d2e9f6a81b902fabdd3d15c282](https://github.com/user-attachments/assets/33fe749b-bcda-45ad-9823-1dcf2f2ccd39)
![aa9885ce53ed344d7591e38076385a9](https://github.com/user-attachments/assets/c6e73c5b-3c99-4745-a19d-eb8488224fe3)
