### ISSUE TITLE
poll error for fd 4 Critical fd 4 got error, exiting

### ISSUE THREAD

**Issue by PeterJBurke** [mavlink-router/mavlink-router#439]
poll error for fd 4
Critical fd 4 got error, exiting

I get this error on Raspbian Bookworm on the latest Mavlink Router build and two different flight controllers. running two different versions of Arducopter.

I have tried it on two different Pi's with two different SD cards and both have the error, suggesting it is not a hardware issue with one of the PIs.

The error causes Mavlink-Router to crash (i.e. exit with error code).

It is intermittent but happens more often than not on boot of the system.

I have installed the latest version of Mavlink Router on a Raspberry Pi Zero 2 W.
Also latest Bookworm Rasbpian with all the updates/upgrades.

With two different flight controllers:
11/3/2024 6:53:38 PM : MatekF405-TE 0046003D 50315015 2033334E
11/3/2024 6:53:38 PM : ChibiOS: 6a85082c
11/3/2024 6:53:38 PM : ArduCopter V4.5.7 (2a3dc4b7)

And 
11/3/2024 7:02:34 PM : FlywooF745 00350041 31355111 31303738
11/3/2024 7:02:34 PM : ChibiOS: 08877972
11/3/2024 7:02:34 PM : ArduCopter V4.1.0-rc4 (6a4fd8a8)

Ardupilot is configured to listen with Mavlink2 on serial at baud 57k.

This is my main.conf file:
[General]
#Mavlink-router serves on this TCP port
TcpServerPort=5678
ReportStats=false
MavlinkDialect=auto
FlowControl=true
#ReportStats=true
#Log=~/mavlink-router
#LogMode=always
#DebugLogLevel=warning

[UartEndpoint bravo]
Device = /dev/serial0
Baud = 57600
#Baud = 9600,19200,38400,57600,115200,500000,921600
#Baud = 921600,500000,115200,57600,38400,19200,9600
#Baud = 115200,921600,57600
FlowControl=true

**Comment by jbeyerstedt** [comment]
From the posted information I can only guess that "fd 4" is the serial link. It's expected that the application closes when there's a fatal error on the serial connection.

Could you start mavlink-router with `-v` to show which endpoint has which file descriptor ID?

**Comment by PeterJBurke** [comment]
Hi here is an update:
it seems this is related to underpower on the Pi.
I was using the flight controller 5V rail to power the Pi that was only able to provide 200 mA.
See https://www.mateksys.com/?portfolio=f405-wmn#tab-id-3
Instead if I switch to the supply rail that can provide 2A , the error seems to go away.
So you may close this ticket as resolved, user error. (User being me).
Apologies for any inconvenience this may have caused to the developers.
